# Micromamba environment file
# https://marketplace.visualstudio.com/items?itemName=corker.vscode-micromamba

name: mlops
channels:
  - conda-forge
dependencies:
  - python>=3.11,<3.12
  - ipykernel
  - jupyter
  - setuptools==59.8.0  
  - scikit-learn>=1.4,<=1.5
  - mlflow>=2.13
  - polars
  - seaborn
  - plotly
  - pip
  # module-02
  - hyperopt
  - xgboost
  - fastparquet
  - boto3
  - awscli
  - localstack
  # module-03
  - shap
  - graphviz
  # module-04
  - requests
  - flask
  - pyarrow
  # module-05
  - tqdm
  - joblib
  - pyarrow
  - evidently 
  - matplotlib
  - pip:
    - psycopg
    - psycopg_binary  
    