# Micromamba environment file
# https://marketplace.visualstudio.com/items?itemName=corker.vscode-micromamba

name: mlops
channels:
  - conda-forge
dependencies:
  - python>=3.11,<3.12
  - ipykernel
  - jupyter
  - setuptools==59.8.0  
  - scikit-learn>0.24.1,<1.5
  - mlflow==2.12.2
  - polars
  - seaborn
  - plotly
  - pip
  # module-02
  - hyperopt
  - xgboost
  - fastparquet
  - boto3
  - awscli
  - localstack
  # module-03
  - shap
  - graphviz
  # - pip:
    