# Micromamba environment file
# https://marketplace.visualstudio.com/items?itemName=corker.vscode-micromamba

name: mlops
channels:
  - conda-forge
dependencies:
  - python>=3.11,<3.12
  - ipykernel
  - jupyter
  - pandas>=2.2
  # - pyarrow (mlflow pre-req)
  - polars
  - seaborn
  - matplotlib
  - plotly
  - scikit-learn>0.24.1,<1.5
  - scikit-learn>0.24.1,<1.5
  - pip
  # module-02
  - setuptools==59.8.0
  - hyperopt
  - xgboost
  - fastparquet
  - boto3
  - awscli
  - pip:
    # non-pip installs picked up older 1.2.0 version
    - mlflow==2.12.2
    